"use client";
import Link from "next/link";
import { useState } from "react";
import { CodeBlock, useSite } from "./site";
import { sdkCode, mcpCode } from "./docs-content";
export default function Developers() {
    const { t, href } = useSite();
    const [tab, setTab] = useState("sdk");
    return <main id="main" className="developers shell"><section className="dev-intro"><span className="eyebrow">ARIADNE / DEVELOPERS</span><h1>{t("Your interface.", "你的界面，", "당신의 인터페이스.")}<br /><em>{t("Our common thread.", "共享的市场脉络。", "하나로 이어지는 시장.")}</em></h1><p>{t("Structured market context for applications, agents and research workflows. Build on the same asset identity, without rebuilding the connection.", "为应用、Agent 与研究流程提供结构化市场信息。共享资产身份，无需重复搭建连接。", "앱, 에이전트, 리서치 워크플로를 위한 구조화된 시장 정보. 동일한 자산 식별 기반으로 구축하세요.")}</p><Link className="button primary" href={href("/docs")}>{t("Start building", "开始构建", "구축 시작")} ↗</Link><span className="dev-version">TYPESCRIPT SDK + MCP / 0.1</span></section>
 <section className="integration-section reveal"><div><span className="eyebrow">{t("CHOOSE YOUR CONNECTION", "选择接入方式", "연결 방식 선택")}</span><h2>{t("Two ways in.\nOne shared core.", "两种接入，\n同一内核。", "두 가지 연결.\n하나의 코어.")}</h2><div className="integration-tabs"><button aria-pressed={tab === "sdk"} onClick={() => setTab("sdk")}><span>01</span><strong>TypeScript SDK</strong><small>{t("For your application", "接入你的应用", "앱에 통합")}</small></button><button aria-pressed={tab === "mcp"} onClick={() => setTab("mcp")}><span>02</span><strong>MCP</strong><small>{t("For existing clients", "连接已有客户端", "기존 클라이언트 연결")}</small></button></div><p>{tab === "sdk" ? t("Run in your server environment. API credentials stay out of the browser. Not limited to Agent applications.", "在服务端运行，API 凭证不进入浏览器。不局限于 Agent 应用。", "서버 환경에서 실행하세요. API 자격 증명은 브라우저에 노출하지 않습니다.") : t("Connect a compatible client to local Demo Mode first. No wallet or credentials required.", "先将兼容客户端接入本地 Demo，无需钱包或凭证。", "먼저 호환 클라이언트를 로컬 데모에 연결하세요. 지갑이나 자격 증명이 필요 없습니다.")}</p><Link className="text-link" href={href("/docs/" + tab)}>{t("Read the integration guide", "阅读接入指南", "연결 가이드 읽기")} ↗</Link></div><CodeBlock code={tab === "sdk" ? sdkCode : mcpCode} label={tab === "sdk" ? "TypeScript · server" : "JSON · Demo Mode"}/></section>
 <section className="capabilities reveal"><span className="eyebrow">{t("PRIMITIVES, NOT ANOTHER SILO", "能力可组合，不再是信息孤岛", "조합 가능한 기본 기능")}</span><h2>{t("Build with context.", "带着上下文，构建。", "맥락을 바탕으로 구축하세요.")}</h2><div>{[[t("Discover", "发现", "탐색"), "TokenizedAsset", t("Company, issuer, chain and contract — identity kept together.", "公司、发行方、链与合约，完整保留资产身份。", "기업, 발행사, 체인, 계약을 함께 유지합니다.")], [t("Compare", "比较", "비교"), "Comparison", t("Read differences across representations, with exclusions preserved.", "对照不同链上表示，并保留排除原因。", "온체인 표현 간 차이와 제외 사유를 보존합니다.")], [t("Understand", "理解", "이해"), "MarketContext", t("Prices, references and warnings. Unknown stays unknown.", "价格、参考值与警告。未知保持未知。", "가격, 참조값, 경고. 알 수 없는 값은 그대로 유지합니다.")]].map(([title, code, body], i) => <article key={code}><small>0{i + 1}</small><h3>{title}</h3><code>{code}</code><p>{body}</p></article>)}</div></section>
 <section className="boundary-panel reveal"><span className="eyebrow">{t("BUILT WITH BOUNDARIES", "明确的能力边界", "명확한 경계")}</span><h2>{t("User control is not an option.", "用户控制权，不是可选项。", "사용자 제어권은 선택 사항이 아닙니다.")}</h2><p>{t("Discovery and research are read-only. Preparation, simulation and execution remain separate. Signing stays external; this website does not expose signing or broadcasting.", "发现与研究保持只读。准备、模拟与执行相互分离。签名由外部完成，本网站不开放签名或广播。", "탐색과 리서치는 읽기 전용입니다. 준비, 시뮬레이션, 실행은 분리되며 서명은 외부에서 처리합니다.")}</p><Link className="text-link" href={href("/docs/safety")}>{t("Explore the boundaries", "了解能力边界", "경계 알아보기")} ↗</Link></section></main>;
}
