import type { Language } from "./copy";
export type Words = [
    string,
    string,
    string
];
export type DocSection = {
    id: string;
    title: Words;
    body: Words;
    code?: string;
    label?: string;
};
export type Doc = {
    slug: string;
    title: Words;
    description: Words;
    sections: DocSection[];
};
export const words = (value: Words, lang: Language) => value[lang === "zh" ? 1 : lang === "ko" ? 2 : 0];
export const sdkCode = 'import { BinanceWeb3Client, TokenizedStocksService }\n  from "ariadne-tokenized-stocks";\n\n// Server-side only. Never expose credentials in browser code.\nconst client = new BinanceWeb3Client({\n  apiKey: process.env.BINANCE_WEB3_API_KEY!,\n  apiSecret: process.env.BINANCE_WEB3_API_SECRET!,\n});\nconst stocks = new TokenizedStocksService(client);\nconst assets = await stocks.search("NVDA", { chainId: "56" });\n\nif (assets[0]) {\n  const context = await stocks.marketContext(assets[0]);\n  console.log(context);\n}';
export const mcpCode = '{\n  "mcpServers": {\n    "ariadne-tokenized-stocks": {\n      "command": "npm",\n      "args": ["run", "mcp:demo"],\n      "cwd": "/absolute/path/to/ariadne-tokenized-stocks"\n    }\n  }\n}';
export const docs: Doc[] = [
    { slug: "start", title: ["Quickstart", "快速开始", "빠른 시작"], description: ["Make your first read-only request. No wallet required.", "发起第一次只读请求，无需钱包。", "지갑 없이 첫 읽기 전용 요청을 시작하세요."], sections: [
            { id: "overview", title: ["Start in Demo Mode", "从 Demo 模式开始", "데모 모드로 시작"], body: ["Ariadne connects asset discovery, issuer comparison and market context. Demo Mode uses deterministic examples, not live prices. It needs no Binance credentials and does not sign or broadcast.", "Ariadne 连接资产发现、发行方比较和市场信息。Demo 使用确定性示例而非实时价格，无需 Binance 凭证，不签名、不广播。", "Ariadne는 자산 탐색, 발행사 비교, 시장 정보를 연결합니다. 데모는 실시간 가격이 아닌 고정 예시를 사용하며 자격 증명이나 서명이 필요 없습니다."] },
            { id: "install", title: ["Run from source", "从源码运行", "소스에서 실행"], body: ["Use the source checkout for this preview. No published npm version is assumed. Run the following from the repository root, then keep the MCP process under your client's control.", "本预览使用源码仓库，不假定 npm 包已发布。在仓库根目录执行以下命令，MCP 进程由客户端管理。", "이 미리보기는 소스 저장소를 사용하며 npm 게시를 가정하지 않습니다. 저장소 루트에서 실행하세요."], label: "Terminal", code: "git clone https://github.com/lant1ng-1216/ariadne-tokenized-stocks.git\ncd ariadne-tokenized-stocks\nnpm install\nnpm run mcp:config:demo" },
            { id: "first-request", title: ["Ask a question", "尝试第一次研究", "첫 리서치 요청"], body: ["Add the generated configuration to an MCP-compatible client. Ask it to research NVIDIA representations and preserve warnings. The client chooses and invokes the tool; this is not a standalone Ariadne chatbot.", "将生成的配置添加到支持 MCP 的客户端。让它研究 NVIDIA 的不同链上表示，并保留警告。由客户端选择并调用工具，这不是一个独立的 Ariadne 聊天机器人。", "생성된 설정을 MCP 클라이언트에 추가하고 NVIDIA 온체인 표현을 조사하도록 요청하세요. 도구 호출은 기존 클라이언트가 담당합니다."], label: "Example prompt", code: "Compare NVIDIA's tokenized representations on BNB Chain.\nShow issuers, reference gaps, missing data and warnings.\nDo not create a transaction." }
        ] },
    { slug: "sdk", title: ["TypeScript SDK", "TypeScript SDK", "TypeScript SDK"], description: ["Structured market capabilities for your application.", "把结构化市场能力接入你的应用。", "앱을 위한 구조화된 시장 기능."], sections: [
            { id: "setup", title: ["Prepare the package", "准备 SDK 包", "패키지 준비"], body: ["Build the SDK from the source repository and create a local package. Install the generated archive in your consuming server application. The package filename includes its current version; use the actual npm pack output.", "在源码仓库构建 SDK 并生成本地包，在调用方的服务端应用中安装该归档。包文件名包含当前版本，以 npm pack 的实际输出为准。", "소스 저장소에서 SDK를 빌드하고 로컬 패키지를 만드세요. 사용하는 서버 앱에 생성된 아카이브를 설치하세요."], label: "Terminal", code: "npm install\nnpm run build\nnpm pack\n# In your consuming server application:\n# npm install /absolute/path/to/generated-package.tgz" },
            { id: "read-assets", title: ["Discover and inspect", "发现并查看资产", "자산 탐색 및 조회"], body: ["Keep API keys and secrets on the server. The SDK is for regular applications and services as well as agent integrations. Check empty results before requesting market context.", "API Key 与 Secret 仅保存在服务端。SDK 面向常规应用、服务以及 Agent 集成。请求市场信息前先检查是否找到资产。", "API 키와 시크릿은 서버에 보관하세요. SDK는 일반 앱, 서비스, 에이전트 통합에 모두 사용할 수 있습니다."], label: "TypeScript / server", code: sdkCode },
            { id: "identity", title: ["Keep the issuer in the identity", "保留发行方身份", "발행사 식별 유지"], body: ["A ticker is not a unique token identity. Preserve the issuer, chain ID and contract address when carrying an asset into a later workflow. Never silently substitute one issuer for another.", "股票代码不是唯一代币身份。进入后续流程时保留发行方、链 ID 和合约地址，不要静默替换发行方。", "티커만으로 토큰을 식별할 수 없습니다. 후속 워크플로에서 발행사, 체인 ID, 계약 주소를 유지하세요."] }
        ] },
    { slug: "mcp", title: ["MCP integration", "MCP 接入", "MCP 연결"], description: ["Extend an existing client. Keep the user in control.", "扩展已有客户端，保留用户控制权。", "기존 클라이언트를 확장하고 사용자 제어권을 유지하세요."], sections: [
            { id: "configuration", title: ["Client configuration", "客户端配置", "클라이언트 설정"], body: ["This example launches local Demo Mode. Replace cwd with the repository's absolute path. Client configuration conventions vary: use the generated config and your client's documented setup flow.", "此示例启动本地 Demo。将 cwd 替换为仓库绝对路径。不同客户端的配置方式可能不同，请结合生成配置与客户端说明使用。", "이 예시는 로컬 데모를 실행합니다. cwd를 저장소의 절대 경로로 바꾸고 클라이언트의 설정 안내를 따르세요."], label: "JSON", code: mcpCode },
            { id: "tools", title: ["High-level tools", "高层工具", "상위 도구"], body: ["Start with research_tokenized_stock for a combined research result. discover_tokenized_assets discovers issuer-aware assets; compare_asset_representations compares their representations. screen_assets_by_preferences applies explicit criteria. Action-preparation tools have separate safety boundaries.", "优先使用 research_tokenized_stock 获取组合研究结果；discover_tokenized_assets 发现含发行方信息的资产；compare_asset_representations 比较链上表示；screen_assets_by_preferences 应用明确筛选条件。行动准备工具有独立安全边界。", "research_tokenized_stock으로 통합 리서치를 시작하세요. 자산 탐색, 온체인 표현 비교, 명시적 조건 필터링 도구도 제공합니다. 거래 준비 도구에는 별도 안전 경계가 있습니다."] },
            { id: "outcomes", title: ["Handle outcomes explicitly", "明确处理返回状态", "결과 상태 처리"], body: ["Inspect outcome.status: success, warning, blocked or error. A blocked result is not permission to retry execution. Preserve warnings and inspect sideEffects before proceeding.", "检查 outcome.status：success、warning、blocked 或 error。blocked 不代表可以重试执行；继续前应保留警告并检查 sideEffects。", "outcome.status의 success, warning, blocked, error를 확인하세요. 차단 결과는 실행 재시도 허가가 아닙니다."] }
        ] },
    { slug: "data", title: ["Data & identity", "数据与资产身份", "데이터 및 자산 식별"], description: ["Understand the fields before you compare them.", "比较之前，先理解字段。", "비교하기 전에 필드를 이해하세요."], sections: [
            { id: "objects", title: ["The market objects", "市场对象", "시장 객체"], body: ["TokenizedAsset identifies the underlying company, issuer, chain and contract. MarketContext adds source-provided price, reference price, state and warnings. Comparison preserves differences; it is not a promise that an order is executable.", "TokenizedAsset 标识底层公司、发行方、链与合约。MarketContext 补充来源提供的价格、参考价格、状态与警告。Comparison 保留差异，不承诺订单可以执行。", "TokenizedAsset은 기초 기업, 발행사, 체인, 계약을 식별합니다. MarketContext는 출처 가격, 참조 가격, 상태 및 경고를 추가합니다."] },
            { id: "gaps", title: ["Missing is not zero", "缺失不等于零", "누락은 0이 아닙니다"], body: ["Unknown market state stays unknown. Missing liquidity or volume must not be rendered as zero. Price differences require comparable reference fields. Display source time when supplied; a fresh fetch does not prove the underlying price is fresh.", "未知的市场状态保持未知。缺失流动性或成交量不能显示为零。价格差异需要可比较的参考字段；提供来源时间时应展示，刚完成请求不等于行情新鲜。", "알 수 없는 시장 상태는 그대로 유지하세요. 누락된 유동성이나 거래량을 0으로 표시하지 마세요. 요청 시간이 최신이라고 가격도 최신인 것은 아닙니다."] },
            { id: "demo", title: ["Demo and live are different", "区分 Demo 与实时来源", "데모와 실시간 구분"], body: ["The local website currently uses the existing read-only Demo service. Its catalog contains several companies; supplementary Demo research currently covers NVIDIA only. Other details show catalog evidence and explicitly mark research coverage gaps.", "当前本地网站使用现有只读 Demo 服务。目录包含多家公司，补充 Demo 研究目前只覆盖 NVIDIA。其他详情展示目录证据，并明确标注研究覆盖缺口。", "현재 로컬 웹사이트는 읽기 전용 데모 서비스를 사용합니다. 카탈로그는 여러 기업을 포함하지만 추가 데모 리서치는 NVIDIA만 지원합니다."] }
        ] },
    { slug: "safety", title: ["Execution boundaries", "执行边界", "실행 경계"], description: ["Research, preparation and execution are separate steps.", "研究、准备与执行，是不同的步骤。", "리서치, 준비, 실행은 별도 단계입니다."], sections: [
            { id: "read-only", title: ["This website is read-only", "本网站的只读边界", "웹사이트의 읽기 전용 경계"], body: ["Asset discovery and comparison do not create transactions. The current website does not accept private keys or seed phrases and does not request signatures or broadcast. Do not interpret a displayed price as a quote you can execute.", "发现与比较资产不创建交易。当前网站不接收私钥或助记词，不请求签名、不广播。展示价格不是可以执行的报价。", "현재 웹사이트는 개인 키나 복구 문구를 받지 않으며 서명이나 브로드캐스트를 요청하지 않습니다. 표시 가격은 실행 가능한 견적이 아닙니다."] },
            { id: "prepare", title: ["Preparation is not execution", "准备不等于执行", "준비는 실행이 아닙니다"], body: ["Core ActionPlan and simulation capabilities are separate from this website. External signing and explicit user confirmation are required at execution boundaries. Funded-wallet end-to-end validation is still a separate outstanding validation task.", "核心 ActionPlan 与模拟能力独立于本网站。执行边界需要外部签名及用户明确确认；真实资金钱包的端到端验证仍是单独待完成的验证任务。", "핵심 ActionPlan 및 시뮬레이션은 웹사이트와 별개입니다. 실행에는 외부 서명과 명시적 확인이 필요하며 실제 자금 지갑의 종단 검증은 별도 미완료 과제입니다."] }
        ] },
    { slug: "errors", title: ["Errors & troubleshooting", "错误与排查", "오류 및 문제 해결"], description: ["Make failures visible and recover safely.", "让失败可见，以安全方式恢复。", "실패를 명확히 표시하고 안전하게 복구하세요."], sections: [
            { id: "service", title: ["Data service unavailable", "数据服务不可用", "데이터 서비스 이용 불가"], body: ["The website shows an error and Retry instead of silently replacing a failed live request with Demo values. Check the local API process and ARIADNE_API_ORIGIN on the server. Browser requests never carry API secrets.", "网站显示错误与重试，不会静默用 Demo 替换失败的实时请求。检查本地 API 进程与服务端 ARIADNE_API_ORIGIN。浏览器请求不携带 API Secret。", "실패한 실시간 요청을 데모 값으로 대체하지 않습니다. 로컬 API 프로세스와 서버의 ARIADNE_API_ORIGIN을 확인하세요."] },
            { id: "partial", title: ["Partial results", "部分结果", "부분 결과"], body: ["Keep usable evidence alongside missingFields and warnings. Empty search results are different from transport failures. Do not infer market availability or trading eligibility from an incomplete response.", "把可用证据与 missingFields、warnings 一起保留。空搜索结果不同于网络失败，不要从不完整响应推断市场开放或交易资格。", "유효한 근거와 missingFields 및 warnings를 함께 유지하세요. 빈 결과는 네트워크 오류와 다르며 불완전한 응답으로 거래 가능 여부를 추측하지 마세요."] }
        ] }
];
