import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const quickstart = await readFile("docs/QUICKSTART.md", "utf8");
const readme = await readFile("README.md", "utf8");
const sdkUsage = await readFile("docs/SDK_USAGE.md", "utf8");
const demoConfig = JSON.parse(await readFile("docs/mcp-config.demo.example.json", "utf8"));
const liveConfig = JSON.parse(await readFile("docs/mcp-config.live.example.json", "utf8"));
assert.match(quickstart, /npm run mcp:demo/);
assert.match(quickstart, /Node\.js `>=22\.19\.0`/);
assert.match(quickstart, /git clone https:\/\/github\.com\/lant1ng-1216\/ariadne-tokenized-stocks\.git[\s\S]*npm ci/);
assert.match(quickstart, /npm run mcp:config:demo[\s\S]*current absolute working directory/);
assert.match(quickstart, /Live Mode[\s\S]*npm run mcp:config:live[\s\S]*Keep `.env` local/);
assert.match(quickstart, /supports automatic tool selection[\s\S]*If it does not, invoke that tool explicitly/i);
assert.match(quickstart, /research_tokenized_stock/);
assert.match(quickstart, /No Binance account, API key or wallet is needed/);
assert.match(quickstart, /Do not trade/);
assert.match(quickstart, /npm run web:demo/);
assert.match(quickstart, /public-address wallet-exposure preview/);
assert.match(readme, /18 MCP tools/);
assert.match(readme, /full prerequisites and setup steps[\s\S]*docs\/QUICKSTART\.md/);
assert.match(readme, /standalone SDK guide/);
assert.match(readme, /npm run mcp:config:demo/);
assert.match(readme, /Tool selection behavior depends on the host and is not guaranteed by Ariadne/);
assert.match(readme, /public Hosted MCP, npm publication/);
assert.match(readme, /npm run web:demo/);
assert.match(sdkUsage, /It is \*\*not published to npm\*\*/);
assert.match(sdkUsage, /git clone https:\/\/github\.com\/lant1ng-1216\/ariadne-tokenized-stocks\.git[\s\S]*npm run build[\s\S]*npm pack/);
assert.match(sdkUsage, /const assets = await stocks\.search\("NVDA", \{ chainId: "56" \}\);[\s\S]*stocks\.marketContext\(asset\)/);
assert.match(sdkUsage, /integrating application owns that UI[\s\S]*must not call `confirm\(\)` solely because an Agent requested it/);
assert.match(sdkUsage, /never stores a wallet private key or signs on behalf of a user/);
assert.match(sdkUsage, /Only an accepted `decision: approve` advances the registry[\s\S]*it does not sign or broadcast/);
assert.match(quickstart, /Real signing and broadcasting remain separate user-wallet operations/);
assert.deepEqual(demoConfig.mcpServers["ariadne-tokenized-stocks"].args, ["run", "mcp:demo"]);
assert.deepEqual(liveConfig.mcpServers["ariadne-tokenized-stocks"].args, ["--env-file=.env", "--import", "tsx", "src/mcp/server.ts"]);
assert.equal(JSON.stringify(demoConfig).includes("BINANCE_WEB3_API_SECRET"), false);
assert.equal(JSON.stringify(liveConfig).includes("BINANCE_WEB3_API_SECRET"), false);
console.log(JSON.stringify({ standaloneSdkPath: true, agentMcpDemoPath: true, liveCredentialsStayLocal: true, toolSelectionClaimsBounded: true, userConfirmationAndExternalSigningBoundaries: true, publicDistributionNotClaimed: true, passed: true }, null, 2));
